//
//  Country.swift
//  moneyXchanger
//
//  Created by Roman Gurung on 3/9/24.
//

enum Country: String, CaseIterable {
    case afghanistan
    case alandIslands
    case albania
    case algeria
    case americanSamoa
    case andorra
    case angola
    case anguilla
    case antiguaAndBarbuda
    case argentina
    case armenia
    case aruba
    case australia
    case austria
    case azerbaijan
    case bahamas
    case bahrain
    case bangladesh
    case barbados
    case belarus
    case belgium
    case belize
    case benin
    case bermuda
    case bhutan
    case bolivia
    case bonaire
    case bosniaAndHerzegovina
    case botswana
    case bouvetIsland
    case brazil
    case britishIndianOceanTerritory
    case bruneiDarussalam
    case bulgaria
    case burkinaFaso
    case burundi
    case caboVerde
    case cambodia
    case cameroon
    case canada
    case caymanIslands
    case centralAfricanRepublic
    case chad
    case chile
    case china
    case christmasIsland
    case cocosIslands
    case colombia
    case comoros
    case congo
    case congoDemocraticRepublic
    case cookIslands
    case costaRica
    case coteDIvoire
    case croatia
    case cuba
    case curacao
    case cyprus
    case czechRepublic
    case denmark
    case djibouti
    case dominica
    case dominicanRepublic
    case ecuador
    case egypt
    case elSalvador
    case equatorialGuinea
    case eritrea
    case estonia
    case eswatini
    case ethiopia
    case falklandIslands
    case faroeIslands
    case fiji
    case finland
    case france
    case frenchGuiana
    case frenchPolynesia
    case frenchSouthernTerritories
    case gabon
    case gambia
    case georgia
    case germany
    case ghana
    case gibraltar
    case greece
    case greenland
    case grenada
    case guadeloupe
    case guam
    case guatemala
    case guernsey
    case guinea
    case guineaBissau
    case guyana
    case haiti
    case heardIslandAndMcDonaldIslands
    case holySee
    case honduras
    case hongKong
    case hungary
    case iceland
    case india
    case indonesia
    case iran
    case iraq
    case ireland
    case isleOfMan
    case israel
    case italy
    case jamaica
    case japan
    case jersey
    case jordan
    case kazakhstan
    case kenya
    case kiribati
    case korea
    case kuwait
    case kyrgyzstan
    case laoPeopleSDemocraticRepublic
    case latvia
    case lebanon
    case lesotho
    case liberia
    case libya
    case liechtenstein
    case lithuania
    case luxembourg
    case macao
    case madagascar
    case malawi
    case malaysia
    case maldives
    case mali
    case malta
    case marshallIslands
    case martinique
    case mauritania
    case mauritius
    case mayotte
    case mexico
    case micronesia
    case moldova
    case monaco
    case mongolia
    case montenegro
    case montserrat
    case morocco
    case mozambique
    case myanmar
    case namibia
    case nauru
    case nepal
    case netherlands
    case newCaledonia
    case newZealand
    case nicaragua
    case niger
    case nigeria
    case niue
    case norfolkIsland
    case northMacedonia
    case northernMarianaIslands
    case norway
    case oman
    case pakistan
    case palau
    case palestine
    case panama
    case papuaNewGuinea
    case paraguay
    case peru
    case philippines
    case pitcairn
    case poland
    case portugal
    case puertoRico
    case qatar
    case reunion
    case romania
    case russianFederation
    case rwanda
    case saintBarthelemy
    case saintHelena
    case saintKittsAndNevis
    case saintLucia
    case saintMartin
    case saintPierreAndMiquelon
    case saintVincentAndTheGrenadines
    case samoa
    case sanMarino
    case saoTomeAndPrincipe
    case saudiArabia
    case senegal
    case serbia
    case seychelles
    case sierraLeone
    case singapore
    case sintMaarten
    case slovakia
    case slovenia
    case solomonIslands
    case somalia
    case southAfrica
    case southGeorgiaAndTheSouthSandwichIslands
    case southSudan
    case spain
    case sriLanka
    case sudan
    case suriname
    case svalbardAndJanMayen
    case sweden
    case switzerland
    case syrianArabRepublic
    case taiwan
    case tajikistan
    case tanzania
    case thailand
    case timorLeste
    case togo
    case tokelau
    case tonga
    case trinidadAndTobago
    case tunisia
    case turkey
    case turkmenistan
    case turksAndCaicosIslands
    case tuvalu
    case uganda
    case ukraine
    case unitedArabEmirates
    case unitedKingdom
    case unitedStates
    case uruguay
    case uzbekistan
    case vanuatu
    case venezuela
    case vietNam
    case virginIslands
    case wallisAndFutuna
    case westernSahara
    case yemen
    case zambia
    case zimbabwe
}
