default_platform(:ios)

platform :ios do
  desc "Run Unit and UI Tests"
  lane :test do
    scan(
      project: "moneyXchanger.xcodeproj",
      scheme: "moneyXchanger",
      devices: ["iPhone 16"],
      test_without_building: false
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    scan(
      project: "moneyXchanger.xcodeproj",
      scheme: "moneyXchanger",
      devices: ["iPhone 16"],
      test_without_building: false
    )
    build_app(
      project: "moneyXchanger.xcodeproj",
      scheme: "moneyXchanger",
      export_method: "app-store"
    )  
    upload_to_testflight  
  end

  desc "Build and upload to App Store"
  lane :appstore do
    scan(
      project: "moneyXchanger.xcodeproj",
      scheme: "moneyXchanger",
      devices: ["iPhone 16"],
      test_without_building: false
    )
    build_app(
      project: "moneyXchanger.xcodeproj",
      scheme: "YourApp",
      export_method: "app-store"
    )  
    upload_to_app_store
  end
end