name: iOS CI/CD with Fastlane & Tests (Manual Deployment)

on:
  push:
    branches:
      - main  # Run tests on push to main
  pull_request:
    branches:
      - main  # Run tests on PRs to main
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Ruby & Bundler
        run: |
          gem install bundler:2.4.22
          bundle install

      - name: Install Dependencies
        run: |
          pod install --project-directory=. || echo "No CocoaPods found, skipping..."

      - name: Run UI & Unit Tests
        run: bundle exec fastlane test

  deploy_testflight:
    if: github.event_name == 'workflow_dispatch'  # Run only when manually triggered
    needs: test
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Ruby & Bundler
        run: |
          gem install bundler:2.4.22
          bundle install

      - name: Install Dependencies
        run: |
          pod install --project-directory=. || echo "No CocoaPods found, skipping..."

      - name: Build & Deploy to TestFlight
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        run: bundle exec fastlane beta

  deploy_appstore:
    if: github.event_name == 'workflow_dispatch'  # Run only when manually triggered
    needs: test
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Ruby & Bundler
        run: |
          gem install bundler:2.4.22
          bundle install

      - name: Install Dependencies
        run: |
          pod install --project-directory=. || echo "No CocoaPods found, skipping..."

      - name: Build & Deploy to App Store
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
        run: bundle exec fastlane appstore
